spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://db:3306/ezbuy?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}

ai:
  classification:
    service:
      url: ${AI_SERVICE_URL:http://ai-service:8000/api/predict}
